color: "#71B180"
copyright: "Copyright hpsof @ 18.09.2020 12:54:17 | "
footer:
  - title: "Über uns"
    content: "bla bla bla blubber... wir sind eine tolle firma
      bla bla bla blubber... wir sind eine tolle firma bla bla bla blubber... 
      wir sind eine tolle firma bla bla bla blubber... wir sind eine tolle firma"
  - title: Neuigkeiten
    recents: blog
    recentCount: 3
  - title: Kontakt
    contact: false 
  - title: Wichtige Links
    menu: true